### ISSUE TITLE
High Xorg CPU usage

### ISSUE THREAD

**Issue by Emru1** [bjesus/air#3]
Hey
I noticed that whenever something moves or changes on the screen (e.g. writting letter in emacs) Xorg CPU usage skyrockets to 100% for 3-5 seconds. I know that Clara does not have hardware acceleration. I was wondering, would lowering framerate with `xrandr` help with this issue?

**Comment by bjesus** [comment]
mmm... sounds like you can easily try and report back? if you find that it helps, I'll happily add that to AIR's startup scripts

**Comment by Emru1** [comment]
Well, no luck there. I've gone as low as 1 FPS, but still `Xorg` CPU usage goes to maximum.

**Comment by bjesus** [comment]
I'm closing this issue as I'm not convinced there's an actual problem here.
