### ISSUE TITLE
AIR installed on a Kobo Clara HD but display not rotated

### ISSUE THREAD

**Issue by thanatow** [bjesus/air#4]
I installed PostmarketOS on my Clara, first trying the "sxmo-de-dwm" ui and then trying the "xfce4" ui as the base and then installing as per your instructions. I can get the Kobo booted into the OS, but the display screen isn't rotated matching the touchscreen. With "sxmo-de-dwm" I installed a device profile as per the "Device Profiles" section of [https://man.sr.ht/~anjan/sxmo-docs-next/SYSTEMGUIDE.md#device-profiles](url), but the screen does not rotate. I have a similar issue with "xfce4" where I can get it to boot and be "useable" but it is in landscape. If I apply your touchscreen rotation config it rotates the touchscreen but not the display so using things is quite impossible. I can use the xrandr command from the device cli to manually rotate the display, but this is only possible if I haven't already applied your rotation config as typing would be otherwise impossible, and as a result, when the display rotates the touchscreen is left in landscape orientation (which your config would fix, but I can't seem to get both applied at the same time.)

I guess my initial question is when you install PostmarketOS, what init options, such as the selected ui, etc are you using before applying your AIR packages on top of it?

(FYI my use case is I am trying to use the Kobo as an e-ink wall control panel for accessing a node-red web interface so all I am trying to get working is a web browser that launches on startup in kiosk mode.)

**Comment by AnnAmelieThema** [comment]
Hey, I found a workaround for this, I don't know why but the awful.spawn.once("xrandr --output None-1 --rotate left") in rc.lua doesn't trigger (or maybe triggers at an inappropriate time?). I've found if I switch to just awful.spawn, it works fine, but I don't know the ramifications of that yet though.
I'm continuing to see if I can figure something out. But thought I'd at least drop this much.

**Comment by AnnAmelieThema** [comment]
In the description for the awful.spawn.once line it says "Note that this also wont work with shell or terminal commands. " So I imagine that is why it doesn't work?

**Comment by bjesus** [comment]
Both `spawn` and `spawn.once`  aren't running shell AFAIK. I think that the only difference is that `once` shouldn't run the command again when AwesomeWM is restarted.

This seems to me like a timing issue. Changing that line to `awful.spawn.with_shell("sleep 3 && xrandr --output None-1 --rotate left")` seems to fix it.

**Comment by bjesus** [comment]
I've updated the config so closing this ticket for now
